#!/usr/bin/env bun
// Embed the built widget bundles into Core (spec §5.2/§5.3).
//
// Reads each `dist/<slug>.html` (the self-contained Vite output), sha256s it, and:
//   - writes the committed artifact `apps/core/src/sidecar/mcp/apps/bundles/<slug>.html`
//   - generates `apps/core/src/sidecar/mcp/apps/generated.rs`, a Rust module that
//     exposes each bundle via `include_str!`, its sha256, and a `html_for_slug` map.
//
// The per-app metadata (server, uri, tools, …) is read from each app's `app.meta.ts`
// (the single source of truth), so the Rust `AppBundle`/`AppToolMeta` entries stay in
// lockstep with the TypeScript definitions.
//
// `--check` recomputes everything from `dist/` and compares against the committed
// files WITHOUT writing, exiting non-zero on any drift (the CI staleness guard behind
// `@ryu/apps#gen:check`).

import { createHash } from "node:crypto";
import { existsSync, readdirSync } from "node:fs";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import type { AppMeta } from "../src/shared/meta";

const scriptDir = import.meta.dir;
const pkgRoot = resolve(scriptDir, "..");
const distDir = resolve(pkgRoot, "dist");
const appsSrcDir = resolve(pkgRoot, "src", "apps");
const coreAppsDir = resolve(
	pkgRoot,
	"..",
	"..",
	"apps",
	"core",
	"src",
	"sidecar",
	"mcp",
	"apps",
);
const bundlesDir = resolve(coreAppsDir, "bundles");
const generatedRsPath = resolve(coreAppsDir, "generated.rs");

const WIDGET_MIME = "text/html+skybridge";
const CHECK = process.argv.includes("--check");

interface EmbeddedApp {
	meta: AppMeta;
	html: string;
	sha256: string;
}

function sha256Hex(text: string): string {
	return createHash("sha256").update(text, "utf8").digest("hex");
}

/** Escape a string for use inside a Rust double-quoted string literal. */
function rustStr(value: string): string {
	return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function appSlugs(): string[] {
	return readdirSync(appsSrcDir, { withFileTypes: true })
		.filter(
			(entry) =>
				entry.isDirectory() &&
				existsSync(resolve(appsSrcDir, entry.name, "app.meta.ts")),
		)
		.map((entry) => entry.name)
		.sort();
}

async function loadMeta(slug: string): Promise<AppMeta> {
	const metaPath = resolve(appsSrcDir, slug, "app.meta.ts");
	const mod = (await import(pathToFileURL(metaPath).href)) as {
		default: AppMeta;
	};
	return mod.default;
}

async function collect(): Promise<EmbeddedApp[]> {
	const apps: EmbeddedApp[] = [];
	for (const slug of appSlugs()) {
		const meta = await loadMeta(slug);
		const htmlPath = resolve(distDir, `${meta.slug}.html`);
		const file = Bun.file(htmlPath);
		if (!(await file.exists())) {
			throw new Error(
				`missing built bundle for "${meta.slug}" at ${htmlPath} — run \`vite build\` first`,
			);
		}
		const html = await file.text();
		apps.push({ meta, html, sha256: sha256Hex(html) });
	}
	return apps;
}

function renderToolMeta(tool: AppMeta["tools"][number]): string {
	const schema = JSON.stringify(tool.inputSchema);
	// A tool renders the app's widget (carries the `outputTemplate` binding) when
	// it is NOT widget-accessible: per spec §6 render/read tools set
	// `widgetAccessible:false`, companion write tools set it `true`. The Core
	// provider (`apps/mcp/apps/mod.rs`) reads `renders_widget` to attach the
	// binding, so it is derived here rather than stored in `app.meta.ts`.
	const rendersWidget = !tool.widgetAccessible;
	return [
		"        AppToolMeta {",
		`            name: ${rustStr(tool.name)},`,
		`            description: ${rustStr(tool.description ?? "")},`,
		`            input_schema: ${rustStr(schema)},`,
		`            renders_widget: ${rendersWidget},`,
		`            widget_accessible: ${tool.widgetAccessible},`,
		`            invoking: ${rustStr(tool.invoking ?? "")},`,
		`            invoked: ${rustStr(tool.invoked ?? "")},`,
		"        },",
	].join("\n");
}

function renderBundle(app: EmbeddedApp): string {
	const { meta, sha256 } = app;
	const tools = meta.tools.map(renderToolMeta).join("\n");
	return [
		"    AppBundle {",
		`        slug: ${rustStr(meta.slug)},`,
		`        server: ${rustStr(meta.server)},`,
		`        name: ${rustStr(meta.name)},`,
		`        uri: ${rustStr(meta.uri)},`,
		`        mime: ${rustStr(WIDGET_MIME)},`,
		`        default_on: ${meta.defaultOn},`,
		`        default_display_mode: ${rustStr(meta.displayMode)},`,
		`        sha256: ${rustStr(sha256)},`,
		`        html: include_str!("bundles/${meta.slug}.html"),`,
		"        tools: &[",
		tools,
		"        ],",
		"    },",
	].join("\n");
}

function renderGeneratedRs(apps: EmbeddedApp[]): string {
	const bundles = apps.map(renderBundle).join("\n");
	return `// @generated by packages/ryu-apps/scripts/embed.ts — DO NOT EDIT BY HAND.
// Run \`bun run --filter @ryu/apps gen\` to regenerate after changing a widget.

/// Metadata for one tool a built-in widget app exposes.
#[derive(Debug, Clone, Copy)]
pub struct AppToolMeta {
    pub name: &'static str,
    pub description: &'static str,
    pub input_schema: &'static str,
    /// True when calling this tool renders the app's widget (carries the
    /// outputTemplate binding). Derived from the inverse of widget_accessible.
    pub renders_widget: bool,
    pub widget_accessible: bool,
    pub invoking: &'static str,
    pub invoked: &'static str,
}

/// A built-in widget app: its identity, its self-contained HTML bundle, and tools.
#[derive(Debug, Clone, Copy)]
pub struct AppBundle {
    pub slug: &'static str,
    pub server: &'static str,
    pub name: &'static str,
    pub uri: &'static str,
    pub mime: &'static str,
    pub default_on: bool,
    pub default_display_mode: &'static str,
    pub sha256: &'static str,
    pub html: &'static str,
    pub tools: &'static [AppToolMeta],
}

/// Every built-in widget app, one entry per roster app.
pub const APP_BUNDLES: &[AppBundle] = &[
${bundles}
];

/// Resolve a slug to its self-contained widget HTML bundle.
pub fn html_for_slug(slug: &str) -> Option<&'static str> {
    APP_BUNDLES
        .iter()
        .find(|bundle| bundle.slug == slug)
        .map(|bundle| bundle.html)
}
`;
}

async function readIfExists(path: string): Promise<string | null> {
	const file = Bun.file(path);
	return (await file.exists()) ? await file.text() : null;
}

async function run(): Promise<void> {
	const apps = await collect();
	const generated = renderGeneratedRs(apps);

	if (CHECK) {
		const drift: string[] = [];
		for (const app of apps) {
			const committed = await readIfExists(
				resolve(bundlesDir, `${app.meta.slug}.html`),
			);
			if (committed !== app.html) {
				drift.push(`bundles/${app.meta.slug}.html is stale`);
			}
		}
		const committedRs = await readIfExists(generatedRsPath);
		if (committedRs !== generated) {
			drift.push("generated.rs is stale");
		}
		if (drift.length > 0) {
			process.stderr.write(
				`ryu-apps embed check failed:\n  ${drift.join("\n  ")}\nRun \`bun run --filter @ryu/apps gen\`.\n`,
			);
			process.exit(1);
		}
		process.stdout.write(
			`ryu-apps embed check: ${apps.length} bundles up to date.\n`,
		);
		return;
	}

	for (const app of apps) {
		await Bun.write(resolve(bundlesDir, `${app.meta.slug}.html`), app.html);
	}
	await Bun.write(generatedRsPath, generated);
	process.stdout.write(
		`ryu-apps embed: wrote ${apps.length} bundles + generated.rs to ${coreAppsDir}\n`,
	);
}

await run();
