//! Capability CLI shims — the broker's verbs as PATH commands (Rivet's
//! binding-as-CLI, adapted to Ryu's capability broker).
//!
//! A sandboxed manifest sidecar (and any child Core spawns with the ext
//! identity) already reaches an abstract capability over HTTP via the broker
//! (`POST /api/host/capability/:cap`, see [`crate::sidecar::ext_proxy`]). This
//! module materializes a per-plugin bin dir of tiny executable **shims** so the
//! same capability is reachable as a plain command:
//!
//! ```text
//! ryu-cap rag '{"op":"retrieve","input":{"query":"…"}}'   # multiplexer
//! ryu-rag-retrieve '{"query":"…"}'                        # convenience alias
//! echo '{"query":"…"}' | ryu-rag-retrieve                 # …or over stdin
//! ```
//!
//! **Credentials stay host-side.** The shim reads `$RYU_EXT_TOKEN` from its
//! runtime env and sends it as the bearer; the token literal is NEVER written
//! into a script file (env-reference only), so the on-disk shims carry no
//! secret and passing tokens on argv is avoided entirely (the wave-2 child-env
//! scrubbers protect the child env). Core injects `RYU_EXT_TOKEN` /
//! `RYU_EXT_PLUGIN_ID` / `RYU_CORE_PORT` at spawn and prepends the shim dir to
//! the child's `PATH`.
//!
//! The multiplexer content is **identical for every plugin** (all per-plugin
//! values arrive via env at runtime); only the convenience aliases bake a
//! capability + verb (both public, never secret). This keeps the generated
//! scripts deterministic (golden-testable) and secret-free.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

/// The per-plugin subdirectory (under `<plugin_dir>`) that holds the generated
/// shims. Kept distinct from the plugin's own `bin/` (downloaded binaries) and
/// `runtime/` (python venvs) so a plugin can never shadow a shim with a payload
/// of the same name.
pub const SHIM_DIRNAME: &str = "cap-shims";

/// The multiplexer command name (POSIX file has no extension so it is callable
/// as `ryu-cap`; Windows uses `ryu-cap.cmd`).
const MUX_NAME: &str = "ryu-cap";

/// Env var the shims read for Core's loopback port. Injected at spawn.
pub const ENV_CORE_PORT: &str = "RYU_CORE_PORT";

/// The broker capabilities that have a fixed, known verb vocabulary (mirrors
/// `packages/sdk` `PRIMITIVE_BINDINGS` broker families). Convenience aliases
/// (`ryu-<cap>-<verb>`) are generated only for the intersection of these and a
/// plugin's DECLARED `requires.capabilities`; the `ryu-cap` multiplexer stays
/// capability-agnostic and covers any other (app-provided) capability the plugin
/// declared. The broker enforces the declared-edge check regardless, so an alias
/// for an unheld capability simply 404s at the door.
const KNOWN_CAP_VERBS: &[(&str, &[&str])] = &[
    ("rag", &["retrieve", "embed", "rerank"]),
    ("memory", &["recall", "store"]),
    ("realtime", &["broadcast", "subscribe"]),
    ("durable", &["checkpoint", "resume"]),
    ("engines", &["embed"]),
];

/// The POSIX `ryu-cap` multiplexer. Constant across plugins (all per-plugin
/// values arrive via env). Usage: `ryu-cap <cap> [--op <verb>] [json]`; the JSON
/// payload comes from the trailing argument, else stdin. With `--op`, the
/// payload is wrapped as `{"op":"<verb>","input":<payload>}` (the broker body
/// shape the SDK's `brokerCall` uses); without it the payload is posted verbatim.
/// Prints the broker's JSON response to stdout and exits nonzero on any non-2xx
/// or transport error.
///
/// Gated to non-Windows (where [`materialize`] writes it) or test builds (both
/// platforms' generators are golden-tested), so the other platform's build does
/// not carry it as dead code.
#[cfg(any(not(windows), test))]
pub fn multiplexer_sh() -> String {
    format!(
        r#"#!/bin/sh
# ryu-cap — Ryu capability broker shim (generated by Core; do not edit).
# Usage: ryu-cap <capability> [--op <verb>] [json-body]
#   Payload comes from the trailing arg, else stdin. With --op the payload is
#   wrapped as {{"op":"<verb>","input":<payload>}}; else it is posted verbatim.
# The bearer is read from $RYU_EXT_TOKEN at runtime — never stored in this file.
set -u

cap="${{1:-}}"
if [ -z "$cap" ]; then
  echo "ryu-cap: usage: ryu-cap <capability> [--op <verb>] [json-body]" >&2
  exit 2
fi
shift

op=""
if [ "${{1:-}}" = "--op" ]; then
  if [ "$#" -lt 2 ]; then
    echo "ryu-cap: --op requires a verb" >&2
    exit 2
  fi
  op="$2"
  shift 2
fi

: "${{{core_port}?{core_port} is not set}}"
: "${{RYU_EXT_TOKEN?RYU_EXT_TOKEN is not set}}"
: "${{RYU_EXT_PLUGIN_ID?RYU_EXT_PLUGIN_ID is not set}}"

if [ "$#" -ge 1 ]; then
  payload="$1"
else
  payload="$(cat)"
fi

if [ -n "$op" ]; then
  body="$(printf '{{"op":"%s","input":%s}}' "$op" "$payload")"
else
  body="$payload"
fi

url="http://127.0.0.1:${{{core_port}}}/api/host/capability/${{cap}}"
tmp="$(mktemp "${{TMPDIR:-/tmp}}/ryu-cap.XXXXXX")" || exit 1
trap 'rm -f "$tmp"' EXIT

code="$(curl -sS -o "$tmp" -w '%{{http_code}}' \
  -X POST "$url" \
  -H "authorization: Bearer ${{RYU_EXT_TOKEN}}" \
  -H "{hdr_plugin}: ${{RYU_EXT_PLUGIN_ID}}" \
  -H 'content-type: application/json' \
  --data-binary "$body")" || exit 1

cat "$tmp"
case "$code" in
  2*) exit 0 ;;
  *) exit 1 ;;
esac
"#,
        core_port = ENV_CORE_PORT,
        hdr_plugin = crate::sidecar::ext_proxy::HDR_PLUGIN_ID,
    )
}

/// The Windows `ryu-cap.cmd` multiplexer. Same contract as [`multiplexer_sh`].
/// JSON-with-quotes on argv is unreliable under `cmd.exe`, so the reliable path
/// on Windows is stdin (the generated aliases always pipe); the trailing-arg
/// form is supported for simple payloads. Gated to Windows or test builds.
#[cfg(any(windows, test))]
pub fn multiplexer_cmd() -> String {
    // `%%` escapes a literal `%` inside a .cmd file; `%%{http_code}` therefore
    // reaches curl as `%{http_code}`.
    format!(
        "@echo off\r\n\
setlocal\r\n\
REM ryu-cap.cmd — Ryu capability broker shim (generated by Core; do not edit).\r\n\
REM Usage: ryu-cap ^<capability^> [--op ^<verb^>] [json-body]  (payload from arg or stdin)\r\n\
REM The bearer is read from %%RYU_EXT_TOKEN%% at runtime — never stored here.\r\n\
if \"%~1\"==\"\" (echo ryu-cap: usage: ryu-cap ^<capability^> [--op ^<verb^>] [json-body] 1>&2 & exit /b 2)\r\n\
set \"CAP=%~1\"\r\n\
shift\r\n\
set \"OP=\"\r\n\
if \"%~1\"==\"--op\" (set \"OP=%~2\" & shift & shift)\r\n\
if \"%{core_port}%\"==\"\" (echo ryu-cap: {core_port} is not set 1>&2 & exit /b 2)\r\n\
if \"%RYU_EXT_TOKEN%\"==\"\" (echo ryu-cap: RYU_EXT_TOKEN is not set 1>&2 & exit /b 2)\r\n\
if \"%RYU_EXT_PLUGIN_ID%\"==\"\" (echo ryu-cap: RYU_EXT_PLUGIN_ID is not set 1>&2 & exit /b 2)\r\n\
set \"URL=http://127.0.0.1:%{core_port}%/api/host/capability/%CAP%\"\r\n\
set \"TMP=%TEMP%\\ryu-cap-%RANDOM%%RANDOM%.json\"\r\n\
if not \"%~1\"==\"\" (set \"PAYLOAD=%~1\") else (set /p PAYLOAD=)\r\n\
if not \"%OP%\"==\"\" (set \"BODY={{\"\"op\"\":\"\"%OP%\"\",\"\"input\"\":%PAYLOAD%}}\") else (set \"BODY=%PAYLOAD%\")\r\n\
for /f \"usebackq delims=\" %%C in (`curl -sS -o \"%TMP%\" -w \"%%{{http_code}}\" -X POST \"%URL%\" -H \"authorization: Bearer %RYU_EXT_TOKEN%\" -H \"{hdr_plugin}: %RYU_EXT_PLUGIN_ID%\" -H \"content-type: application/json\" --data-binary \"%BODY%\"`) do set \"CODE=%%C\"\r\n\
if exist \"%TMP%\" type \"%TMP%\"\r\n\
if exist \"%TMP%\" del \"%TMP%\" >nul 2>&1\r\n\
if \"%CODE:~0,1%\"==\"2\" (exit /b 0) else (exit /b 1)\r\n",
        core_port = ENV_CORE_PORT,
        hdr_plugin = crate::sidecar::ext_proxy::HDR_PLUGIN_ID,
    )
}

/// The POSIX convenience alias `ryu-<cap>-<verb>`. Delegates to the sibling
/// `ryu-cap` (resolved dir-relative so it works regardless of PATH ordering),
/// forwarding stdin and any trailing payload arg. All the HTTP/auth logic lives
/// once, in the multiplexer. Gated to non-Windows or test builds.
#[cfg(any(not(windows), test))]
pub fn alias_sh(cap: &str, verb: &str) -> String {
    format!(
        r#"#!/bin/sh
# ryu-{cap}-{verb} — convenience alias for `ryu-cap {cap} --op {verb}`.
# Generated by Core; do not edit. Wraps the input JSON (trailing arg or stdin)
# and delegates to the sibling ryu-cap multiplexer.
set -u
dir="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
exec "$dir/{mux}" {cap} --op {verb} "$@"
"#,
        mux = MUX_NAME,
    )
}

/// The Windows convenience alias `ryu-<cap>-<verb>.cmd`. Delegates to the
/// sibling `ryu-cap.cmd`, forwarding stdin (piped) and any trailing payload arg.
/// Gated to Windows or test builds.
#[cfg(any(windows, test))]
pub fn alias_cmd(cap: &str, verb: &str) -> String {
    format!(
        "@echo off\r\n\
REM ryu-{cap}-{verb}.cmd — convenience alias for `ryu-cap {cap} --op {verb}`.\r\n\
REM Generated by Core; do not edit.\r\n\
\"%~dp0{mux}.cmd\" {cap} --op {verb} %*\r\n",
        mux = MUX_NAME,
    )
}

/// The `(cap, verb)` alias pairs to generate for a plugin's DECLARED capability
/// set: the intersection of [`KNOWN_CAP_VERBS`] with `declared`. Order is stable
/// (KNOWN_CAP_VERBS order) for deterministic materialization.
fn alias_pairs(declared: &[String]) -> Vec<(&'static str, &'static str)> {
    let mut out = Vec::new();
    for (cap, verbs) in KNOWN_CAP_VERBS {
        if declared.iter().any(|d| d == cap) {
            for verb in *verbs {
                out.push((*cap, *verb));
            }
        }
    }
    out
}

/// The **program names** [`materialize`] writes for `declared` — the `ryu-cap`
/// multiplexer plus one convenience alias per declared known-capability verb, in
/// the same stable order. These are the base names a sandboxed caller invokes on
/// PATH (`ryu-cap`, `ryu-rag-retrieve`, …); the Deno PTC lowering passes them as a
/// scoped `--allow-run=<names>` allow-list (Deno matches the spawned program NAME,
/// not a directory), so the sandbox may spawn only the generated shims.
///
/// Base names, no extension: on Windows the on-disk files carry `.cmd`, but a
/// caller invokes them by base name (PATHEXT resolves the file), which is what
/// Deno's allow-run matches. (The `.cmd`-exact form is a documented Windows
/// follow-up should a caller ever spawn with the literal extension.)
pub fn shim_names(declared: &[String]) -> Vec<String> {
    let mut names = vec![MUX_NAME.to_owned()];
    for (cap, verb) in alias_pairs(declared) {
        names.push(format!("ryu-{cap}-{verb}"));
    }
    names
}

/// Materialize the shim dir under `plugin_dir` and return its path. Writes the
/// platform-appropriate `ryu-cap` multiplexer plus a convenience alias for each
/// declared known capability verb. Idempotent: re-run at every spawn to refresh
/// content (the scripts are tiny and secret-free). On unix the scripts are made
/// executable (`0755`).
///
/// `declared` is the plugin's `requires.capabilities` names — the multiplexer is
/// always written (it handles any capability), so an empty `declared` still
/// yields a working `ryu-cap`, just no convenience aliases.
pub async fn materialize(plugin_dir: &Path, declared: &[String]) -> anyhow::Result<PathBuf> {
    let dir = plugin_dir.join(SHIM_DIRNAME);
    tokio::fs::create_dir_all(&dir).await?;

    let pairs = alias_pairs(declared);

    #[cfg(windows)]
    {
        write_shim(&dir.join(format!("{MUX_NAME}.cmd")), &multiplexer_cmd()).await?;
        for (cap, verb) in &pairs {
            write_shim(
                &dir.join(format!("ryu-{cap}-{verb}.cmd")),
                &alias_cmd(cap, verb),
            )
            .await?;
        }
    }
    #[cfg(not(windows))]
    {
        write_shim(&dir.join(MUX_NAME), &multiplexer_sh()).await?;
        for (cap, verb) in &pairs {
            write_shim(&dir.join(format!("ryu-{cap}-{verb}")), &alias_sh(cap, verb)).await?;
        }
    }

    Ok(dir)
}

/// Write one shim file and, on unix, mark it executable.
async fn write_shim(path: &Path, content: &str) -> anyhow::Result<()> {
    tokio::fs::write(path, content).await?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        tokio::fs::set_permissions(path, std::fs::Permissions::from_mode(0o755)).await?;
    }
    Ok(())
}

/// Prepend `shim_dir` to the child's `PATH` in `env` (layered over Core's
/// inherited PATH) and inject [`ENV_CORE_PORT`] if the caller has not already set
/// it. The single seam both the manifest-sidecar and BYO-agent spawn paths use so
/// the shims resolve on PATH and know where Core listens.
pub fn inject_shim_env(env: &mut BTreeMap<String, String>, shim_dir: &Path) {
    // Prefer a PATH already staged in `env` (a caller may have set one), else the
    // inherited process PATH the child would otherwise see.
    let base = env
        .get("PATH")
        .map(std::ffi::OsString::from)
        .or_else(|| std::env::var_os("PATH"));

    let mut paths = vec![shim_dir.to_path_buf()];
    if let Some(existing) = base {
        paths.extend(std::env::split_paths(&existing));
    }
    if let Ok(joined) = std::env::join_paths(paths) {
        env.insert("PATH".to_owned(), joined.to_string_lossy().into_owned());
    }

    env.entry(ENV_CORE_PORT.to_owned())
        .or_insert_with(core_port_string);
}

/// Core's own loopback port as a string, resolved the same way
/// [`crate::sidecar::gateway::core_self_url`] does (RYU_BIND → profile default),
/// so a profile-shifted dev/custom Core injects the port it actually listens on.
pub fn core_port_string() -> String {
    let default_port = crate::profile::port(7980);
    match std::env::var("RYU_BIND") {
        Ok(bind) => bind
            .rsplit_once(':')
            .and_then(|(_, p)| p.trim().parse::<u16>().ok())
            .unwrap_or(default_port)
            .to_string(),
        Err(_) => default_port.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn multiplexer_sh_is_secret_free_and_env_referenced() {
        let s = multiplexer_sh();
        // Golden invariants: env-referenced token (never a literal), the exact
        // broker path + plugin-id header, and a nonzero exit on non-2xx.
        assert!(s.starts_with("#!/bin/sh"));
        assert!(s.contains("Bearer ${RYU_EXT_TOKEN}"));
        assert!(s.contains("x-ryu-plugin-id: ${RYU_EXT_PLUGIN_ID}"));
        assert!(s.contains("/api/host/capability/${cap}"));
        assert!(s.contains("${RYU_CORE_PORT}"));
        // The multiplexer bakes NO capability, NO plugin id, NO token literal.
        assert!(!s.contains("ryu-local"));
        // Wrapping shape matches the SDK broker body {op, input}.
        assert!(s.contains(r#"{"op":"%s","input":%s}"#));
        // Non-2xx → exit 1.
        assert!(s.contains("2*) exit 0"));
    }

    #[test]
    fn multiplexer_cmd_escapes_http_code_and_reads_env() {
        let s = multiplexer_cmd();
        assert!(s.starts_with("@echo off"));
        // `%%{http_code}` in-file reaches curl as `%{http_code}`.
        assert!(s.contains("%%{http_code}"));
        assert!(s.contains("authorization: Bearer %RYU_EXT_TOKEN%"));
        assert!(s.contains("x-ryu-plugin-id: %RYU_EXT_PLUGIN_ID%"));
        assert!(s.contains("/api/host/capability/%CAP%"));
        // CRLF line endings for cmd.exe.
        assert!(s.contains("\r\n"));
    }

    #[test]
    fn alias_sh_delegates_to_multiplexer_with_op() {
        let s = alias_sh("rag", "retrieve");
        assert!(s.starts_with("#!/bin/sh"));
        assert!(s.contains(r#"exec "$dir/ryu-cap" rag --op retrieve "$@""#));
        // No inline auth/token in an alias — it delegates.
        assert!(!s.contains("RYU_EXT_TOKEN"));
    }

    #[test]
    fn alias_cmd_delegates_dir_relative() {
        let s = alias_cmd("memory", "store");
        assert!(s.contains(r#""%~dp0ryu-cap.cmd" memory --op store %*"#));
    }

    #[test]
    fn shim_names_are_mux_plus_declared_aliases() {
        // Always the multiplexer; aliases only for declared known caps, in order.
        assert_eq!(shim_names(&[]), vec!["ryu-cap".to_owned()]);
        assert_eq!(
            shim_names(&["memory".to_owned()]),
            vec![
                "ryu-cap".to_owned(),
                "ryu-memory-recall".to_owned(),
                "ryu-memory-store".to_owned(),
            ]
        );
        // An unknown (app-provided) cap contributes no alias — the mux covers it.
        assert_eq!(
            shim_names(&["com.acme.widgets".to_owned()]),
            vec!["ryu-cap".to_owned()]
        );
    }

    #[test]
    fn alias_pairs_intersect_declared_with_known_verbs() {
        // Only declared caps get aliases; unknown caps get none (mux covers them).
        let declared = vec!["rag".to_owned(), "com.acme.widgets".to_owned()];
        let pairs = alias_pairs(&declared);
        assert_eq!(
            pairs,
            vec![("rag", "retrieve"), ("rag", "embed"), ("rag", "rerank")]
        );
        // No declared caps → no aliases.
        assert!(alias_pairs(&[]).is_empty());
    }

    #[tokio::test]
    async fn materialize_writes_multiplexer_and_declared_aliases() {
        let tmp = std::env::temp_dir().join(format!("ryu-shim-test-{}", std::process::id()));
        let _ = tokio::fs::remove_dir_all(&tmp).await;
        let dir = materialize(&tmp, &["memory".to_owned()])
            .await
            .expect("materialize");
        assert_eq!(dir, tmp.join(SHIM_DIRNAME));

        #[cfg(not(windows))]
        {
            assert!(dir.join("ryu-cap").exists());
            assert!(dir.join("ryu-memory-recall").exists());
            assert!(dir.join("ryu-memory-store").exists());
            // A non-declared cap's alias is absent.
            assert!(!dir.join("ryu-rag-retrieve").exists());
            // Executable bit set.
            use std::os::unix::fs::PermissionsExt;
            let mode = tokio::fs::metadata(dir.join("ryu-cap"))
                .await
                .unwrap()
                .permissions()
                .mode();
            assert_eq!(mode & 0o111, 0o111, "shim must be executable");

            // The generated scripts must be syntactically valid POSIX sh. `sh -n`
            // parses without executing; a format!-interpolation slip (an unbalanced
            // brace, a stray `{`) fails here. Skipped honestly if sh is unavailable.
            for script in ["ryu-cap", "ryu-memory-recall", "ryu-memory-store"] {
                if let Ok(status) = std::process::Command::new("sh")
                    .arg("-n")
                    .arg(dir.join(script))
                    .status()
                {
                    assert!(status.success(), "{script} is not valid POSIX sh");
                }
            }
        }
        #[cfg(windows)]
        {
            assert!(dir.join("ryu-cap.cmd").exists());
            assert!(dir.join("ryu-memory-recall.cmd").exists());
        }

        let _ = tokio::fs::remove_dir_all(&tmp).await;
    }

    #[test]
    fn inject_shim_env_prepends_path_and_sets_port() {
        let mut env = BTreeMap::new();
        env.insert("PATH".to_owned(), "/usr/bin".to_owned());
        let shim = PathBuf::from("/plugins/acme/cap-shims");
        inject_shim_env(&mut env, &shim);

        let path = env.get("PATH").unwrap();
        assert!(
            path.starts_with(&shim.to_string_lossy().into_owned()),
            "shim dir must be first on PATH: {path}"
        );
        assert!(path.contains("/usr/bin"));
        assert!(env.contains_key(ENV_CORE_PORT));
    }

    #[test]
    fn inject_shim_env_preserves_caller_core_port() {
        let mut env = BTreeMap::new();
        env.insert(ENV_CORE_PORT.to_owned(), "9999".to_owned());
        inject_shim_env(&mut env, &PathBuf::from("/x/cap-shims"));
        assert_eq!(env.get(ENV_CORE_PORT).unwrap(), "9999");
    }
}
