//! models.dev-backed model catalog (the dynamic source that replaces hardcoded
//! model lists).
//!
//! Pi's own model table (`@earendil-works/pi-ai/models.generated.js`) is *generated
//! from* <https://models.dev> ("auto-generated by scripts/generate-models.ts"), so
//! models.dev is the authoritative upstream for "what models does provider X have".
//! We fetch its clean JSON registry (`https://models.dev/api.json`), cache it to
//! disk (24h TTL, last-good fallback offline), and expose a provider → models
//! lookup. This is the discovery-first-with-fallback pattern applied to the whole
//! catalog: a live provider `GET /v1/models` is preferred (see `discover_models`),
//! models.dev fills in when there's no key, and a tiny static seed is the last
//! resort — nothing about the model list is hardcoded per release.
//!
//! Placement (CLAUDE.md §1): read-only model *metadata* for the picker — Core.

use std::path::PathBuf;
use std::time::{Duration, SystemTime};

use serde_json::{Map, Value};

/// Public registry URL. Swappable via `RYU_MODELS_DEV_URL` (nothing hardcoded).
fn registry_url() -> String {
    std::env::var("RYU_MODELS_DEV_URL")
        .ok()
        .filter(|s| !s.trim().is_empty())
        .unwrap_or_else(|| "https://models.dev/api.json".to_owned())
}

/// On-disk cache path for the fetched registry.
fn cache_path() -> PathBuf {
    let dir = crate::sidecar::download_manager::ryu_dir().join("cache");
    let _ = std::fs::create_dir_all(&dir);
    dir.join("models-dev.json")
}

/// How long a cached registry is considered fresh before we refetch.
const CACHE_TTL: Duration = Duration::from_secs(24 * 60 * 60);

/// Map a Ryu/Pi provider id to the models.dev provider key when they differ.
/// Most ids match 1:1; this covers the known divergences (and points the
/// subscription providers at their underlying model family).
fn models_dev_key(provider_id: &str) -> &str {
    match provider_id {
        // Subscription providers reuse the underlying vendor's models.
        "openai-codex" => "openai",
        "claude-pro-max" => "anthropic",
        // Known key spelling differences on models.dev.
        "zai" | "zai-coding-cn" => "z-ai",
        "moonshotai-cn" => "moonshotai",
        "minimax-cn" => "minimax",
        other => other,
    }
}

/// Read the cached registry if present and fresh; else `None`.
fn read_fresh_cache() -> Option<Value> {
    let path = cache_path();
    let meta = std::fs::metadata(&path).ok()?;
    let modified = meta.modified().ok()?;
    let age = SystemTime::now().duration_since(modified).ok()?;
    if age > CACHE_TTL {
        return None;
    }
    let raw = std::fs::read_to_string(&path).ok()?;
    serde_json::from_str(&raw).ok()
}

/// Read the cached registry regardless of age (stale-but-usable offline fallback).
fn read_any_cache() -> Option<Value> {
    let raw = std::fs::read_to_string(cache_path()).ok()?;
    serde_json::from_str(&raw).ok()
}

/// Fetch the registry from models.dev and write it to the cache. Short timeout so
/// a slow/unreachable host degrades to the cached/seed path quickly.
async fn fetch_and_cache() -> Option<Value> {
    let client = reqwest::Client::new();
    let resp = client
        .get(registry_url())
        .timeout(Duration::from_secs(10))
        .send()
        .await
        .ok()?;
    if !resp.status().is_success() {
        return None;
    }
    let body: Value = resp.json().await.ok()?;
    if !body.is_object() {
        return None;
    }
    if let Ok(pretty) = serde_json::to_string(&body) {
        let _ = std::fs::write(cache_path(), pretty);
    }
    Some(body)
}

/// Load the registry: fresh cache → network (refresh) → stale cache. `None` only
/// when there is no cache and the network is unreachable.
async fn load_registry() -> Option<Value> {
    if let Some(fresh) = read_fresh_cache() {
        return Some(fresh);
    }
    if let Some(fetched) = fetch_and_cache().await {
        return Some(fetched);
    }
    read_any_cache()
}

/// The models models.dev knows for a provider, as `[{ id, name }]` (deduped,
/// name-fallback to id). Empty when the provider/registry is unavailable — callers
/// fall back to live `/v1/models` discovery or free-text entry.
pub async fn models_for(provider_id: &str) -> Vec<Value> {
    let Some(registry) = load_registry().await else {
        return vec![];
    };
    let key = models_dev_key(provider_id);
    let Some(models) = registry
        .get(key)
        .and_then(|p| p.get("models"))
        .and_then(Value::as_object)
    else {
        return vec![];
    };
    let mut out: Vec<Value> = Vec::with_capacity(models.len());
    for (id, model) in models {
        let mut entry = Map::new();
        entry.insert("id".to_owned(), Value::String(id.clone()));
        let name = model
            .get("name")
            .and_then(Value::as_str)
            .unwrap_or(id)
            .to_owned();
        entry.insert("name".to_owned(), Value::String(name));
        out.push(Value::Object(entry));
    }
    // Stable order so the picker doesn't reshuffle between reads.
    out.sort_by(|a, b| {
        a["id"]
            .as_str()
            .unwrap_or("")
            .cmp(b["id"].as_str().unwrap_or(""))
    });
    out
}
