//! OpenAPI spec for the Core HTTP API, generated from the Axum handlers.
//!
//! Handlers are annotated with `#[utoipa::path(...)]` next to their definition in
//! `server/mod.rs`; this module collects them into one [`ApiDoc`]. As a child of
//! `server`, it can reference the parent's private handler functions (and the
//! `__path_*` items the macro generates beside them).
//!
//! The spec is consumed two ways:
//! - `ryu-core --dump-openapi` prints it (used by `apps/fumadocs` to render the
//!   interactive API reference; see `apps/fumadocs/scripts/generate-docs.ts`).
//! - `GET /api/openapi.json` serves it from a running Core.
//!
//! Adding an endpoint is mechanical: put `#[utoipa::path(...)]` on the handler,
//! then add it to the `paths(...)` list below.

use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "Ryu Core API",
        version = "0.1.0",
        description = "The local Ryu Core orchestration backend. Default bind 127.0.0.1:7980 (override with --bind / RYU_BIND). When RYU_TOKEN is set, protected routes require `Authorization: Bearer <RYU_TOKEN>`; health and auth routes are public.",
        license(name = "Apache-2.0")
    ),
    servers((url = "http://localhost:7980", description = "Local Core")),
    tags(
        (name = "Health", description = "Liveness, version, and updates."),
        (name = "Auth", description = "Device authorization flow."),
        (name = "Nodes", description = "Node initialization."),
        (name = "Sidecars", description = "Engine/tool/agent install + lifecycle."),
        (name = "Models", description = "Model catalog (HF GGUF) + device fit."),
        (name = "Catalog", description = "Per-kind catalog sources."),
        (name = "Skills", description = "Agent Skills install + activation."),
        (name = "Engines", description = "Engine runtimes + active-engine swap."),
        (name = "Plugins", description = "Plugin (app) catalog + lifecycle."),
        (name = "Agents", description = "Agent CRUD, catalog, import/export."),
        (name = "Teams", description = "Agent teams + members."),
        (name = "MCP", description = "MCP servers, tools, catalog, sandbox."),
        (name = "Tools", description = "Unified tool catalog (search/describe) + PTC exec."),
        (name = "Chat", description = "Chat, channels, delegation."),
        (name = "Retrieval", description = "Chunk indexing + search."),
        (name = "Conversations", description = "Conversations, sessions, goals, runs."),
        (name = "Spaces", description = "Spaces/RAG documents + embeddings."),
        (name = "Downloads", description = "Download center."),
        (name = "Worktree", description = "Per-run git worktrees."),
        (name = "Gateway", description = "Gateway config/status/audit (proxied)."),
        (name = "Workflows", description = "Workflow DAG engine."),
        (name = "Preferences", description = "Cross-surface preferences KV."),
    ),
    paths(
        super::health,
        super::get_version,
        super::auth_status,
        super::update_check,
        super::update_apply,
        super::node_init,
        super::auth_login,
        super::auth_logout,
        super::get_catalog,
        super::models_catalog_list,
        super::models_catalog_detail,
        super::models_catalog_install,
        super::models_catalog_uninstall,
        super::models_device,
        super::models_engines,
        super::system_info_handler,
        super::catalog_sources_list,
        super::catalog_sources_add,
        super::catalog_sources_select,
        super::skills_catalog_list,
        super::skills_catalog_detail,
        super::skills_catalog_install,
        super::skills_install_from_source,
        super::skills_activate,
        super::list_skills,
        super::list_engines,
        super::engine_models,
        super::system_status,
        super::list_apps,
        super::list_apps_catalog,
        super::install_app_from_url,
        super::reload_app_manifests,
        super::install_app_handler,
        super::enable_app_handler,
        super::disable_app_handler,
        super::update_app_handler,
        super::list_agents,
        super::create_agent,
        super::list_agent_catalog,
        super::install_agent_handler,
        super::uninstall_agent_handler,
        super::import_agent,
        super::get_agent,
        super::update_agent,
        super::delete_agent,
        super::export_agent,
        super::list_tools,
        super::migrate_to_ryu,
        super::get_pi_config,
        super::put_pi_config,
        super::get_pi_config_catalog,
        super::configure_pi_provider,
        super::delete_pi_provider,
        super::discover_pi_models,
        super::acp_authenticate,
        super::list_acp_sessions_handler,
        super::delete_acp_session_handler,
        super::agent_update_check,
        super::agent_update,
        super::list_teams,
        super::create_team,
        super::get_team,
        super::update_team,
        super::delete_team,
        super::add_team_member,
        super::remove_team_member,
        super::list_mcp_servers,
        super::create_mcp_server,
        super::list_mcp_tools,
        super::call_mcp_tool,
        super::tools_search,
        super::tools_describe,
        super::tools_exec,
        super::tools_exec_resume,
        super::identity_api::list_identities,
        super::identity_api::create_connection,
        super::identity_api::begin_login,
        super::identity_api::poll_connection,
        super::identity_api::import_connection,
        super::identity_api::delete_connection,
        super::mesh_status,
        super::webhook_ingress_status,
        super::webhook_ingress_get_backend,
        super::webhook_ingress_set_backend,
        super::mcp_catalog_list,
        super::mcp_catalog_detail,
        super::mcp_catalog_install,
        super::sandbox_enable,
        super::sandbox_disable,
        super::sandbox_status,
        super::chat_stream,
        super::chat_cancel,
        super::channel_run,
        super::index_retrieval_chunk,
        super::search_retrieval,
        super::list_conversations,
        super::search_conversations_handler,
        super::get_conversation,
        super::delete_conversation,
        super::fork_conversation,
        super::set_conversation_pinned_handler,
        super::set_conversation_archived_handler,
        super::set_conversation_title_handler,
        super::get_participants_handler,
        super::add_participant_handler,
        super::remove_participant_handler,
        super::list_runs_handler,
        super::runs_stream,
        super::get_run_trace_handler,
        super::create_session_handler,
        super::get_session_handler,
        super::update_session_status_handler,
        super::list_sessions_for_conversation_handler,
        super::list_agent_threads_handler,
        super::import_agent_thread_handler,
        super::data_admin::data_counts,
        super::data_admin::data_clear,
        super::list_spaces,
        super::create_space,
        super::delete_space,
        super::list_documents,
        super::ingest_document,
        super::get_document,
        super::update_document,
        super::delete_document,
        super::create_page,
        super::search_space,
        super::get_embedding_model,
        super::set_embedding_model,
        super::trigger_reindex,
        super::reindex_status,
        super::oai_chat_completions,
        super::list_installed,
        super::get_install_status,
        super::get_install_status_by_name,
        super::install_sidecar,
        super::uninstall_sidecar,
        super::uninstall_sidecar_with_data,
        super::check_installed,
        super::list_downloads,
        super::downloads_stream,
        super::download_pause,
        super::download_resume,
        super::download_retry,
        super::download_cancel,
        super::download_clear,
        super::check_dependencies,
        super::install_dependencies,
        super::sidecar_status,
        super::sidecar_start_all,
        super::sidecar_stop_all,
        super::sidecar_start,
        super::sidecar_stop,
        super::sidecar_restart,
        super::get_active_engine,
        super::set_active_engine,
        super::get_active_model,
        super::set_active_model,
        super::worktree_diff_handler,
        super::worktree_apply_handler,
        super::gateway_get_config,
        super::gateway_put_config,
        super::gateway_status,
        super::gateway_set_provider,
        super::gateway_run_evals,
        super::gateway_audit,
        super::list_workflows,
        super::create_workflow,
        super::get_workflow,
        super::delete_workflow,
        super::run_workflow,
        super::get_workflow_run,
        super::resume_workflow_run,
        super::delegate_stream,
        super::preferences_stream,
        super::get_preference,
        super::set_preference,
    )
)]
pub struct ApiDoc;

/// `GET /api/openapi.json` — serve the generated spec from a running Core.
pub async fn serve_openapi() -> axum::Json<utoipa::openapi::OpenApi> {
    axum::Json(ApiDoc::openapi())
}
